name: playstation_games_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

  equatable: ^2.0.3

  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.6

  get_it: ^7.6.6

  intl: ^0.19.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_html: ^3.0.0-alpha.6
  shimmer: ^3.0.0
  flutter_svg: ^0.23.0+1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf

  assets:
    - assets/image/
    - assets/image/svg/
